[package]
name = "processing_http_requests"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.9.0"
serde = {version = "1.0.215", features = ["derive"] }
serde_json = "1.0.133"
actix-service = "2.0.2"
futures = "0.3.31"
actix-cors = "0.7.0"
